// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1) {
  return window['go']['main']['App']['AddTodo'](arg1);
}

export function GetAllTodos() {
  return window['go']['main']['App']['GetAllTodos']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function RemoveTodo(arg1) {
  return window['go']['main']['App']['RemoveTodo'](arg1);
}

export function SaveLanguage(arg1) {
  return window['go']['main']['App']['SaveLanguage'](arg1);
}

export function UpadateTodo(arg1, arg2) {
  return window['go']['main']['App']['UpadateTodo'](arg1, arg2);
}
