// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTodo(arg1:string):Promise<Array<main.Task>>;

export function GetAllTodos():Promise<Array<main.Task>>;

export function GetLanguage():Promise<string>;

export function RemoveTodo(arg1:number):Promise<Array<main.Task>>;

export function SaveLanguage(arg1:string):Promise<void>;

export function UpadateTodo(arg1:boolean,arg2:number):Promise<Array<main.Task>>;
